#!/usr/bin/env bash

user=$(logname)
workdir=$(pwd)

sudo -u $user docker run -i \
    -t \
    -v /:/host \
    -w /host/${workdir} \
    twgit /usr/local/bin/twgit $@
sudo docker rm twgit > /dev/null 2>&1
